[package]
name = "waybat"
version = "0.1.0"
edition = "2021"

[dependencies]
tray-item = { version = "0.10.0", features = ["libappindicator"] }
gtk = "0.18"
battery = "0.7.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
